services:
  - type: web
    name: pneumovision
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: DISABLE_LOCAL_RAG
        value: "true"
      - key: DISABLE_GRADCAM
        value: "true"
      - key: TORCH_NUM_THREADS
        value: "1"
